DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'agenthub') THEN
    CREATE ROLE agenthub LOGIN PASSWORD 'agenthub';
  ELSE
    ALTER ROLE agenthub WITH LOGIN PASSWORD 'agenthub';
  END IF;
END $$;

GRANT CONNECT ON DATABASE agenthub TO agenthub;
GRANT USAGE, CREATE ON SCHEMA public TO agenthub;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO agenthub;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO agenthub;
